name: Wii (devkitPro)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  wii:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          path: schismtracker

      - name: 'Install build dependencies'
        run: |
          apt-get update
          apt-get install -y ninja-build autoconf automake libtool libsdl2-dev gettext

      - name: 'Get date of latest commit'
        id: date
        run: |
          cd schismtracker
          echo "date=$(git log -n 1 --date=short --format=format:%cd | sed 's/\(....\)-\(..\)-\(..\).*/\1\2\3/')" >> $GITHUB_OUTPUT
          cd ..

      - name: 'Build Schism'
        run: |
          cd schismtracker
          autoreconf -i
          mkdir build
          cd build
          export PATH="${DEVKITPRO}/portlibs/wii/bin:${DEVKITPPC}/bin:$PATH"
          # if we don't build with FLAC support it's an error
          ../configure --host=powerpc-eabi --with-flac
          make
          powerpc-eabi-strip -S schismtracker.elf
          mkdir -p up/apps
          cp -r ../sys/wii/schismtracker up/apps
          mv schismtracker.elf up/apps/schismtracker/boot.elf
          wget https://raw.githubusercontent.com/xiph/flac/master/COPYING.Xiph
          cp ../docs/configuration.md ../README.md ../COPYING COPYING.Xiph up/apps/schismtracker

      - name: 'Upload binary'
        uses: actions/upload-artifact@v4
        with:
          name: schismtracker-${{ steps.date.outputs.date }}-wii
          path: schismtracker/build/up
